language: elixir
otp_release:
  - 20.2
elixir:
  - 1.6.0
before_script:
  - export DB_USERNAME=postgres
  - export DB_PASSWORD=postgres
  - export DB_HOSTNAME=localhost
  - MIX_ENV=test mix ecto.reset
script:
  - mix test
  - mix format --check-formatted
